### PR TITLE
Small tweak to reflect Symfony moving console to /bin/

### PR DESCRIPTION
**Pull request by SecondeJK**
I know it's a really small change, sorry!
Just a tiny tweak to reflect Symfony moving the console to /bin/ from the /app/ folder.

### CODE REVIEW

**Comment by LogansUA** [comment]
@SecondeJK hey thanks, But can you please move this PR to 2.x branch? All fixes/features which related to Symfony3 should be in 2.x branch.

**Comment by LogansUA** [comment]
@SecondeJK ? :smile:

**Comment by SecondeJK** [comment]
Sorry for the delay, making sure I commit to the 2.0 branch. Trying to get a first Pull Request right! :)

**Comment by LogansUA** [comment]
Okey, than i close this?

**Comment by SecondeJK** [comment]
I'll close it and resubmit correctly! Thanks.

**Pull request closed without merging**
