### PR TITLE
Update to sf7

### PR DESCRIPTION
**Pull request by toxicity1985**
Hello, 

I update the bundle to be compatible with SF7.
I also had the auto wiring.

Best regards

### CODE REVIEW

**Comment by parijke** [comment]
Can confirm that it also works on 6.4

**Review by parijke — APPROVED** [review]

**Comment by bresam** [comment]
This fixes also an existing bug with sf6 related to twig service became private.
+1 for merge

**Comment by toxicity1985** [comment]
Hellon

@fre5h @Huron, can you check this merge request ? I think it will help some people.

Best regards.

**Comment by Gemineye** [comment]
Hi, are there any news on this issue?

**Comment by toxicity1985** [comment]
@Gemineye 

I receive no answer about that. If you want i can create a new repository on my side. It will be more updated I think.
I don't want to do that but if it's necessary.

**Comment by Gemineye** [comment]
@toxicity1985 I switched the repository to your 3.2 version and its working. Good enough for me.. Hopefully we can switch back one day ;)

**Comment by umpirsky** [comment]
Can we merge this?

**Pull request merged**
