### PR TITLE
Outsourced TinyMCE

### PR DESCRIPTION
**Pull request by MisatoTremor**
* Add tinymce/tinymce as requirement to composer.json
* Move TinyMCE languages to own directory
* Update language file handling to check for existing default territory expansion
* Remove embedded TinyMCE

Similar to how [MopaBootstrapBundle](http://github.com/phiamo/MopaBootstrapBundle) handles this:
* Add symlink and mirror commands for external TinyMCE
* Add symlink and mirror script handler for composer

### CODE REVIEW

**Comment by tristanbes** [comment]
show this PR some love. It's a pain to propose a PR each time there is a TinyMCE update....

**Comment by MisatoTremor** [comment]
Rebased and squashed

**Comment by tristanbes** [comment]
Super great, thanks, now it's time to call NSA and get @stfalcon to answer on #167 ;-)

**Comment by zanardigit** [comment]
If you're interested, we forked this to https://github.com/gibilogic/tinymce-bundle and we plan to publish on Packagist soon. We thought about the same solution, i.e. remove TinyMCE from bundle and add it as a dependency. We are happy to accept your PR there. :-)

**Comment by LogansUA** [comment]
@MisatoTremor hello. Can you send us a new clear PR with this feature?

**Pull request closed without merging**
