### PR TITLE
Update TinyMCE to 4.2.1

### PR DESCRIPTION
**Pull request by zanardigit**

### CODE REVIEW

**Comment by tristanbes** [comment]
I've upgraded to more recent in this PR https://github.com/stfalcon/TinymceBundle/pull/166

**Comment by zanardigit** [comment]
Ok. Unfortunately, the real issue here is getting our PRs merged. I'm seriously considering forking the project.

**Comment by zanardigit** [comment]
Closing this in favour of #166.

**Comment by tristanbes** [comment]
Forking is not a good solution, naming a new maintainer is: #167 167

**Comment by zanardigit** [comment]
@tristanbes catch 22 here. If the project is **really** abandoned, no new maintainer will be ever named. Forking it's not that bad, if it's meant to solve a dead end. A lot of great open source projects were born as forks :-)

Let's keep in touch about how to fix this. Thank you for your cooperation.

**Comment by nykopol** [comment]
i would use this bundle in my app if it was maintained, but the lack of maintenance will make me switch to a homemade solution witch i don't like. I'm very interested if someone take the lead on this bundle.

**Comment by RubenHarms** [comment]
@zanardigit Just fork it! The first unsolved pull request is on 13 Jun 2014 by MisatoTremor. I guess that @stfalcon is dead or quit his career as developer ;)  @zanardigit  Forking is not a good solution, but there aint no better way, unless you want to wait 4 months.

**Comment by zanardigit** [comment]
@RubenHarms @tristanbes @nykopol ok, green light, we will proceed to fork it and will let you know the new location. Thank you very much for your feedback to this issue.

**Comment by nykopol** [comment]
Great i was waiting for that. I've already did some work on my fork that you can maybe take.

**Comment by zanardigit** [comment]
Forked repo: https://github.com/gibilogic/tinymce-bundle. It will be published on packagist as soon as possible. You can start sending your PRs there.

**Pull request closed without merging**
