### PR TITLE
Feature update tinymce

### PR DESCRIPTION
**Pull request by LogansUA**
- Update TinyMCE to 4.3.2

### CODE REVIEW

**Comment by mitrae** [comment]
@LogansUA any ETA?

**Comment by LogansUA** [comment]
@mitrae I should test it before merge, but i really don't have time to do that.

**Comment by shakaran** [comment]
@LogansUA would be nice if you get a bit of time for test it and merge to master. :+1: to me for merge

**Comment by nykopol** [comment]
@shakaran this is also a change we fixed in [gibilogic fork](https://github.com/gibilogic/tinymce-bundle.git). With our fork you're not stick with one version, you can select you desired version with composer.

**Pull request closed without merging**
