### PR TITLE
Update init.standard.js

### PR DESCRIPTION
**Pull request by averichev**

### CODE REVIEW

**Comment by nallias** [comment]
Description: fix selector option when specifying a classname (and un-force textarea element to allow usage of tinymce inline)

**Comment by naitsirch** [comment]
@stfalcon Could you please merge this PR. It fixes #227

**Comment by naitsirch** [comment]
@fre5h Thanks :) could you add a tag/release, too? Otherwise the fix does not get installed via composer.

**Comment by fre5h** [comment]
@naitsirch v2.4.0

**Comment by naitsirch** [comment]
Any idea why packagist does not notice the new version?
-> https://packagist.org/packages/stfalcon/tinymce-bundle

**Comment by fre5h** [comment]
@naitsirch I've asked @stfalcon to setup autoupdate hook (or to check why it is broken) for packagist. Because I don't have access to settings of this repository. I think it can take some time, because @stfalcon is lazy :(

**Comment by naitsirch** [comment]
No problem. I had to fork the repo anyway, cherry-pick the bugfix and merge it on top of v2.2.0, because I am sitting on PHP 7.0. I just saw it to late. Otherwise I would not have nudged you ;-)

**Comment by fre5h** [comment]
@naitsirch 2.4 appeared in packagist

**Pull request merged**
